--- 
	files: 
	  - 
		destination: /var/www/html/
		source: /index.html
	hooks: 
	  ApplicationStop: 
		- 
		  location: scripts/stop_server
		  runas: root
		  timeout: 300
	  BeforeInstall: 
		- 
		  location: scripts/install_dependencies
		  runas: root
		  timeout: 300
		- 
		  location: scripts/start_server
		  runas: root
		  timeout: 300
	os: linux
	version: 0.0